const makeType = (names) => `/**
 * This was generated by script/prepareType
 * Please DO NOT change it manually.
 */

declare module "react-native-ionicons" {
  import * as React from "react";
  import { TextProps } from "react-native";

  export default class Icon extends React.PureComponent<IconProps> {}

  export interface IconProps extends TextProps {
    name?: IconName;
    ios?: IconName;
    android?: IconName;
    color?: string;
    size?: number;
  }

  export type IconName = ${names.join("\n    | ")};
}
`;

const quoteName = ({ name }) => `"${name}"`;

/**
 * @typedef IconData
 * @property {string} name
 * @property {string} path
 * @property {number} code
 *
 * @param {IconData[]} list
 * @returns {string}
 */
module.exports = function prepareType(list) {
  return makeType(list.map(quoteName));
};
